// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// The request message containing the user's name.
type HelloRequest struct {
	Common *CommonRequest `protobuf:"bytes,1,opt,name=common" json:"common,omitempty"`
	Name   string         `protobuf:"bytes,10,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *HelloRequest) GetCommon() *CommonRequest {
	if m != nil {
		return m.Common
	}
	return nil
}

// The response message containing the greetings
type HelloReply struct {
	Common  *CommonResponse `protobuf:"bytes,1,opt,name=common" json:"common,omitempty"`
	Message string          `protobuf:"bytes,10,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *HelloReply) GetCommon() *CommonResponse {
	if m != nil {
		return m.Common
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "service.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "service.HelloReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/service.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor1,
}

func init() { proto.RegisterFile("service.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x15, 0x84, 0xda, 0x32, 0x14, 0x81, 0x8c, 0x80, 0x28, 0x62, 0x51, 0xb2, 0xea, 0xca,
	0x11, 0x45, 0xe2, 0x00, 0x65, 0x41, 0x97, 0x55, 0xba, 0xe8, 0xda, 0xa4, 0xa3, 0x34, 0x92, 0xed,
	0x31, 0x19, 0x53, 0xc8, 0x96, 0x2b, 0x70, 0x34, 0xae, 0xc0, 0x41, 0x50, 0xfe, 0x2a, 0x54, 0x76,
	0x33, 0xcf, 0xf3, 0xbe, 0x27, 0x3f, 0x38, 0x63, 0x2c, 0x77, 0x45, 0x86, 0xd2, 0x95, 0xe4, 0x49,
	0x0c, 0xbb, 0x35, 0x1a, 0x67, 0x64, 0x0c, 0xd9, 0x56, 0x8e, 0x6e, 0x73, 0xa2, 0x5c, 0x63, 0xa2,
	0x5c, 0x91, 0x28, 0x6b, 0xc9, 0x2b, 0x5f, 0x90, 0xe5, 0xf6, 0x35, 0x4e, 0x61, 0xbc, 0x40, 0xad,
	0x29, 0xc5, 0xd7, 0x37, 0x64, 0x2f, 0x24, 0x0c, 0x5a, 0x77, 0x18, 0x4c, 0x82, 0xe9, 0xe9, 0xec,
	0x5a, 0xf6, 0x21, 0x4f, 0x8d, 0xdc, 0xdd, 0xa5, 0xdd, 0x95, 0x10, 0x70, 0x6c, 0x95, 0xc1, 0x10,
	0x26, 0xc1, 0xf4, 0x24, 0x6d, 0xe6, 0x78, 0x0d, 0xd0, 0x31, 0x9d, 0xae, 0x44, 0x72, 0x40, 0xbc,
	0xf9, 0x47, 0x64, 0x47, 0x96, 0x71, 0x8f, 0x0c, 0x61, 0x68, 0x90, 0x59, 0xe5, 0x3d, 0xb5, 0x5f,
	0x67, 0x2b, 0x18, 0x3e, 0x97, 0x88, 0x1e, 0x4b, 0xb1, 0x80, 0xd1, 0x4a, 0x55, 0x4d, 0x8c, 0xb8,
	0xda, 0x13, 0xff, 0x7e, 0x25, 0xba, 0x3c, 0x94, 0x9d, 0xae, 0xe2, 0x8b, 0xcf, 0xef, 0x9f, 0xaf,
	0x23, 0x10, 0xa3, 0x64, 0x77, 0x9f, 0x60, 0xb6, 0xa5, 0xf9, 0x23, 0xdc, 0x65, 0x64, 0xe4, 0x86,
	0x3d, 0x57, 0x1e, 0x0d, 0x4b, 0xfc, 0x50, 0xc6, 0x69, 0x64, 0xb9, 0xad, 0x6d, 0xef, 0x54, 0xea,
	0xcd, 0xfc, 0xbc, 0x41, 0xac, 0xeb, 0x79, 0x59, 0xf7, 0xb6, 0x0c, 0x5e, 0x06, 0x4d, 0x81, 0x0f,
	0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x34, 0x3a, 0x35, 0xba, 0x86, 0x01, 0x00, 0x00,
}
